/* autogenerated from messages.mc */

#include <nms_common.h>

#include <unicode.h>

const TCHAR *g_szMessages[] = {
	_T(""),
	_T("NetXMS NetFlow/IPFIX Collector started"),
	_T("WSAStartup failed: %1"),
	_T("IPFIX library initialization failed"),
	_T("IPFIX collector registration failed"),
	_T("Unable to start IPFIX listener for %1 protocol"),
	_T("Collector thread started"),
	_T("Collector thread stopped"),
	_T("IPFIX polling error"),
	_T("%1"),
	_T("%1"),
	_T("Unable to establish connection with database (%1)"),
	_T("SQL query failed (Query = \"%1\"): %2")
};

unsigned int g_dwNumMessages = 13;
